var menus = {
1: 'Flammkuchen', 
2: 'Focaccia di recco', 
3: 'Polpette al pomodoro con puree o polenta', 
4: 'Fajitas alla carne o tofu', 
5: 'Pasta carbonara', 
6: 'Pasta salmone e panna', 
7: 'Patate a spicchi al forno', 
8: 'Focaccia di recco', 
9: 'Pasta salmone e panna', 
10: 'Püree', 
11: 'Salmone con verdurine al forno', 
12: 'Insalata pomodoro mozzarella', 
13: 'Minestrina con pastina', 
14: 'Salmone con verdurine al forno', 
15: 'Tortilla espanola', 
16: 'Spezzatino con puree o polenta', 
17: 'Insalata pomodoro mozzarella', 
18: 'Patate a spicchi al forno', 
19: 'Panizza', 
20: 'Fajitas alla carne o tofu', 
21: 'Insalata di riso', 
22: 'Ossibuchi di vitello con puree', 
23: 'Focaccia di recco', 
24: 'Püree', 
25: 'Minestra d\'avena', 
26: 'Spezzatino con puree o polenta', 
27: 'Carne con insalata', 
28: 'Spätzli agli spinaci', 
29: 'Pasta pesto, sugo, burro', 
30: 'Flammkuchen', 
31: 'Crèpes ricotta e spinaci'
};