var menus = {
1: 'Omelette con zucchine a cerchiolini', 
2: 'Püree', 
3: 'Insalata di riso', 
4: 'Lenticchie con sugo di pomodoro e verdurine', 
5: 'Lasagne', 
6: 'Flammkuchen', 
7: 'Ossibuchi di vitello con puree', 
8: 'Pasta carbonara', 
9: 'Carne con insalata', 
10: 'Polenta', 
11: 'Hummus con patate o fajitas', 
12: 'Spätzli agli spinaci', 
13: 'Minestra d\'avena', 
14: 'Insalata pomodoro mozzarella', 
15: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
16: 'Berner Rösti', 
17: 'Tortilla espanola', 
18: 'Pasta salmone e panna', 
19: 'Risotto zafferano', 
20: 'Risotto salmone e verdurine', 
21: 'Curry rosso al latte di cocco', 
22: 'Fajitas alla carne o tofu', 
23: 'Patate a spicchi al forno', 
24: 'Pizza', 
25: 'Focaccia di recco', 
26: 'Minestrina con pastina', 
27: 'Insalatona à la jiji', 
28: 'Salmone con verdurine al forno', 
29: 'Panizza', 
30: 'Pasta pesto, sugo, burro'
};