var menus08 = {
1: 'Risotto salmone e verdurine', 
2: 'Pasta carbonara', 
3: 'Pasta salmone e panna', 
4: 'Minestrina con pastina', 
5: 'Spezzatino con puree o polenta', 
6: 'Insalata pomodoro mozzarella', 
7: 'Püree', 
8: 'Minestra d\'avena', 
9: 'Pizza', 
10: 'Polenta', 
11: 'Salmone con verdurine al forno', 
12: 'Tortilla espanola', 
13: 'Insalata di riso', 
14: 'Risotto zafferano', 
15: 'Pasta bolognese', 
16: 'Erdnusspoulet con riso ', 
17: 'Panizza', 
18: 'Pasta pesto, sugo, burro', 
19: 'Curry rosso al latte di cocco', 
20: 'Crèpes ricotta e spinaci', 
21: 'Pollo e patate al forno', 
22: 'Patate e fagiolini verdi al vapore', 
23: 'Flammkuchen', 
24: 'Polpette al pomodoro con puree o polenta', 
25: 'Omelette con zucchine a cerchiolini', 
26: 'Gratin di patate', 
27: 'Minestra carote e patate e braciole', 
28: 'Lenticchie con sugo di pomodoro e verdurine', 
29: 'Ossibuchi di vitello con puree', 
30: 'Insalatona à la jiji', 
31: 'Fajitas alla carne o tofu'
};
var menus09 = {
1: 'Insalatona à la jiji', 
2: 'Pasta bolognese', 
3: 'Risotto salmone e verdurine', 
4: 'Lenticchie con sugo di pomodoro e verdurine', 
5: 'Lasagne', 
6: 'Gratin di patate', 
7: 'Pizza', 
8: 'Minestrina con pastina', 
9: 'Focaccia di recco', 
10: 'Berner Rösti', 
11: 'Polpette al pomodoro con puree o polenta', 
12: 'Curry rosso al latte di cocco', 
13: 'Omelette con zucchine a cerchiolini', 
14: 'Hummus con patate o fajitas', 
15: 'Minestra d\'avena', 
16: 'Risotto zafferano', 
17: 'Insalata di riso', 
18: 'Insalata pomodoro mozzarella', 
19: 'Polenta', 
20: 'Pasta pesto, sugo, burro', 
21: 'Chili con carne e riso', 
22: 'Püree', 
23: 'Pollo e patate al forno', 
24: 'Tortilla espanola', 
25: 'Crèpes ricotta e spinaci', 
26: 'Panizza', 
27: 'Minestra carote e patate e braciole', 
28: 'Erdnusspoulet con riso ', 
29: 'Flammkuchen', 
30: 'Pasta al currygiallo, latte di cocco e Chinakohl'
};
