var menus = {
1: 'Focaccia di recco', 
2: 'Omelette con zucchine tagliate a cerchiolini', 
3: 'Patate al forno con pollo', 
4: 'Patate e fagiolini a vapore', 
5: 'Rösti', 
6: 'Insalatona à la jiji', 
7: 'Patate al forno con pollo', 
8: 'Carne insalata', 
9: 'Minestra d\'avena', 
10: 'Rotes Curry', 
11: 'Carbonara, insalatina', 
12: 'Rösti con polpette al pomodoro', 
13: 'Fajitas alla carne o tofu', 
14: 'Pasta al pesto o bolognese', 
15: 'Riso e Curryrosso con latte dicocco e tofu/carne', 
16: 'Lasagne', 
17: 'Carbonara', 
18: 'Fajitas alla carne o tofu', 
19: 'Bolognese', 
20: 'Lasagne', 
21: 'Patate e Bohnen e carote nella pentola a vapore', 
22: 'Polpette al pomodoro', 
23: 'Risotto speck e zucchine', 
24: 'Pizza', 
25: 'curry giallo con chinakohl e ingwer', 
26: 'Rösti con speck', 
27: 'Gratin patate, carne carote dampfkoch', 
28: 'Focaccia di recco', 
29: 'Berner Rösti', 
30: 'Risotto zafferano', 
31: 'Pizzette rotonde'
};