var menus11 = {
1: 'Insalatona à la jiji', 
2: 'Spätzli agli spinaci', 
3: 'Panizza', 
4: 'Risotto salmone e verdurine', 
5: 'Patate a spicchi al forno', 
6: 'Polenta', 
7: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
8: 'Pizza', 
9: 'Insalata di riso', 
10: 'Fajitas alla carne o tofu', 
11: 'Omelette con zucchine a cerchiolini', 
12: 'Pollo e patate al forno', 
13: 'Curry rosso al latte di cocco', 
14: 'Chili con carne e riso', 
15: 'Lasagne', 
16: 'Lenticchie con sugo di pomodoro e verdurine', 
17: 'Berner Rösti', 
18: 'Crèpes ricotta e spinaci', 
19: 'Salmone con verdurine al forno', 
20: 'Minestra carote e patate e braciole', 
21: 'Pasta pesto, sugo, burro', 
22: 'Ossibuchi di vitello con puree', 
23: 'Risotto speck e zucchine', 
24: 'Insalata pomodoro mozzarella', 
25: 'Spätzli agli spinaci', 
26: 'Polenta', 
27: 'Minestrina con pastina', 
28: 'Risotto salmone e verdurine', 
29: 'Flammkuchen', 
30: 'Hummus con patate o fajitas', 
31: 'Spätzli'
};
