var menus12 = {
1: 'Carne con insalata', 
2: 'Insalata di riso', 
3: 'Lasagne', 
4: 'Risotto zafferano', 
5: 'Insalatona à la jiji', 
6: 'Salmone con verdurine al forno', 
7: 'Crèpes ricotta e spinaci', 
8: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
9: 'Pizza', 
10: 'Minestrina con pastina', 
11: 'Flammkuchen', 
12: 'Minestra d\'avena', 
13: 'Berner Rösti', 
14: 'Hummus con patate o fajitas', 
15: 'Risotto speck e zucchine', 
16: 'Gratin di patate', 
17: 'Pollo e patate al forno', 
18: 'Curry rosso al latte di cocco', 
19: 'Focaccia di recco', 
20: 'Erdnusspoulet con riso ', 
21: 'Tortilla espanola', 
22: 'Insalatona à la jiji', 
23: 'Spätzli agli spinaci', 
24: 'Minestra carote e patate e braciole', 
25: 'Püree', 
26: 'Pasta pesto, sugo, burro', 
27: 'Chili con carne e riso', 
28: 'Panizza', 
29: 'Minestrina con pastina', 
30: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
31: 'Insalata pomodoro mozzarella'
};
