var menus06 = {
1: 'Polenta', 
2: 'Risotto speck e zucchine', 
3: 'Insalatona à la jiji', 
4: 'Tortilla espanola', 
5: 'Pasta bolognese', 
6: 'Omelette con zucchine a cerchiolini', 
7: 'Lasagne', 
8: 'Salmone con verdurine al forno', 
9: 'Lenticchie con sugo di pomodoro e verdurine', 
10: 'Risotto salmone e verdurine', 
11: 'Curry rosso al latte di cocco', 
12: 'Patate a spicchi al forno', 
13: 'Hummus con patate o fajitas', 
14: 'Flammkuchen', 
15: 'Focaccia di recco', 
16: 'Pollo e patate al forno', 
17: 'Berner Rösti', 
18: 'Risotto speck e zucchine', 
19: 'Püree', 
20: 'Minestrina con pastina', 
21: 'Tortilla espanola', 
22: 'Polpette al pomodoro con puree o polenta', 
23: 'Pasta salmone e panna', 
24: 'Minestra carote e patate e braciole', 
25: 'Panizza', 
26: 'Spätzli agli spinaci', 
27: 'Risotto salmone e verdurine', 
28: 'Fajitas alla carne o tofu', 
29: 'Chili con carne e riso', 
30: 'Pasta al currygiallo, latte di cocco e Chinakohl'
};
