var menus09 = {
1: 'Minestrina con pastina', 
2: 'Pizza', 
3: 'Salmone con verdurine al forno', 
4: 'Panizza', 
5: 'Berner Rösti', 
6: 'Ossibuchi di vitello con puree', 
7: 'Risotto salmone e verdurine', 
8: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
9: 'Insalatona à la jiji', 
10: 'Erdnusspoulet con riso ', 
11: 'Pasta bolognese', 
12: 'Lenticchie con sugo di pomodoro e verdurine', 
13: 'Spätzli', 
14: 'Crèpes ricotta e spinaci', 
15: 'Curry rosso al latte di cocco', 
16: 'Fajitas alla carne o tofu', 
17: 'Insalata pomodoro mozzarella', 
18: 'Focaccia di recco', 
19: 'Polenta', 
20: 'Chili con carne e riso', 
21: 'Püree', 
22: 'Pasta pesto, sugo, burro', 
23: 'Risotto speck e zucchine', 
24: 'Flammkuchen', 
25: 'Polpette al pomodoro con puree o polenta', 
26: 'Minestra carote e patate e braciole', 
27: 'Minestra d\'avena', 
28: 'Pasta salmone e panna', 
29: 'Omelette con zucchine a cerchiolini', 
30: 'Lasagne'
};
