var menus05 = {
1: 'Pasta bolognese', 
2: 'Risotto salmone e verdurine', 
3: 'Gratin di patate', 
4: 'Minestrina con pastina', 
5: 'Insalata di riso', 
6: 'Spätzli', 
7: 'Polpette al pomodoro con puree o polenta', 
8: 'Pizza', 
9: 'Lenticchie con sugo di pomodoro e verdurine', 
10: 'Polenta', 
11: 'Minestra d\'avena', 
12: 'Panizza', 
13: 'Carne con insalata', 
14: 'Pasta pesto, sugo, burro', 
15: 'Curry rosso al latte di cocco', 
16: 'Spezzatino con puree o polenta', 
17: 'Erdnusspoulet con riso ', 
18: 'Omelette con zucchine a cerchiolini', 
19: 'Chili con carne e riso', 
20: 'Risotto salmone e verdurine', 
21: 'Berner Rösti', 
22: 'Spätzli agli spinaci', 
23: 'Minestrina con pastina', 
24: 'Risotto speck e zucchine', 
25: 'Focaccia di recco', 
26: 'Patate e fagiolini verdi al vapore', 
27: 'Minestra carote e patate e braciole', 
28: 'Pasta salmone e panna', 
29: 'Panizza', 
30: 'Polpette al pomodoro con puree o polenta', 
31: 'Insalata pomodoro mozzarella'
};
