var menus01 = {
1: 'Salmone con verdurine al forno', 
2: 'Tortilla espanola', 
3: 'Pasta bolognese', 
4: 'Risotto zafferano', 
5: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
6: 'Flammkuchen', 
7: 'Insalatona à la jiji', 
8: 'Polpette al pomodoro con puree o polenta', 
9: 'Focaccia di recco', 
10: 'Spätzli', 
11: 'Erdnusspoulet con riso ', 
12: 'Insalata di riso', 
13: 'Patate e fagiolini verdi al vapore', 
14: 'Minestra d\'avena', 
15: 'Insalata pomodoro mozzarella', 
16: 'Minestra carote e patate e braciole', 
17: 'Püree', 
18: 'Polenta', 
19: 'Pasta bolognese', 
20: 'Salmone con verdurine al forno', 
21: 'Pasta salmone e panna', 
22: 'Panizza', 
23: 'Risotto speck e zucchine', 
24: 'Hummus con patate o fajitas', 
25: 'Polpette al pomodoro con puree o polenta', 
26: 'Curry rosso al latte di cocco', 
27: 'Spätzli agli spinaci', 
28: 'Tortilla espanola', 
29: 'Omelette con zucchine a cerchiolini', 
30: 'Insalata di riso', 
31: 'Pasta carbonara'
};
