var menus01 = {
1: 'Spezzatino con puree o polenta', 
2: 'Risotto zafferano', 
3: 'Risotto speck e zucchine', 
4: 'Insalata di riso', 
5: 'Pasta carbonara', 
6: 'Ossibuchi di vitello con puree', 
7: 'Pasta pesto, sugo, burro', 
8: 'Panizza', 
9: 'Pizza', 
10: 'Minestrina con pastina', 
11: 'Hummus con patate o fajitas', 
12: 'Minestra d\'avena', 
13: 'Omelette con zucchine a cerchiolini', 
14: 'Erdnusspoulet con riso ', 
15: 'Risotto salmone e verdurine', 
16: 'Flammkuchen', 
17: 'Carne con insalata', 
18: 'Pasta salmone e panna', 
19: 'Pollo e patate al forno', 
20: 'Polenta', 
21: 'Risotto zafferano', 
22: 'Insalatona à la jiji', 
23: 'Spätzli agli spinaci', 
24: 'Patate a spicchi al forno', 
25: 'Fajitas alla carne o tofu', 
26: 'Pasta carbonara', 
27: 'Curry rosso al latte di cocco', 
28: 'Insalata pomodoro mozzarella', 
29: 'Risotto speck e zucchine', 
30: 'Ossibuchi di vitello con puree', 
31: 'Patate e fagiolini verdi al vapore'
};
