var menus02 = {
1: 'Minestrina con pastina', 
2: 'Patate e fagiolini verdi al vapore', 
3: 'Pollo e patate al forno', 
4: 'Ossibuchi di vitello con puree', 
5: 'Focaccia di recco', 
6: 'Patate a spicchi al forno', 
7: 'Curry rosso al latte di cocco', 
8: 'Pasta bolognese', 
9: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
10: 'Insalata pomodoro mozzarella', 
11: 'Insalatona à la jiji', 
12: 'Omelette con zucchine a cerchiolini', 
13: 'Pizza', 
14: 'Minestra carote e patate e braciole', 
15: 'Spätzli', 
16: 'Risotto salmone e verdurine', 
17: 'Spätzli agli spinaci', 
18: 'Püree', 
19: 'Patate e fagiolini verdi al vapore', 
20: 'Risotto speck e zucchine', 
21: 'Erdnusspoulet con riso ', 
22: 'Focaccia di recco', 
23: 'Chili con carne e riso', 
24: 'Flammkuchen', 
25: 'Ossibuchi di vitello con puree', 
26: 'Insalata pomodoro mozzarella', 
27: 'Minestra d\'avena', 
28: 'Fajitas alla carne o tofu'
};
