var menus05 = {
1: 'Risotto salmone e verdurine', 
2: 'Minestrina con pastina', 
3: 'Curry rosso al latte di cocco', 
4: 'Tortilla espanola', 
5: 'Fajitas alla carne o tofu', 
6: 'Spätzli agli spinaci', 
7: 'Risotto zafferano', 
8: 'Patate e fagiolini verdi al vapore', 
9: 'Gratin di patate', 
10: 'Pasta carbonara', 
11: 'Salmone con verdurine al forno', 
12: 'Spezzatino con puree o polenta', 
13: 'Pizza', 
14: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
15: 'Risotto speck e zucchine', 
16: 'Püree', 
17: 'Pasta bolognese', 
18: 'Hummus con patate o fajitas', 
19: 'Lenticchie con sugo di pomodoro e verdurine', 
20: 'Flammkuchen', 
21: 'Spätzli', 
22: 'Fajitas alla carne o tofu', 
23: 'Insalata pomodoro mozzarella', 
24: 'Erdnusspoulet con riso ', 
25: 'Carne con insalata', 
26: 'Insalatona à la jiji', 
27: 'Salmone con verdurine al forno', 
28: 'Pasta salmone e panna', 
29: 'Tortilla espanola', 
30: 'Chili con carne e riso', 
31: 'Pasta al currygiallo, latte di cocco e Chinakohl'
};
