var menus07 = {
1: 'Polpette al pomodoro con puree o polenta', 
2: 'Focaccia di recco', 
3: 'Risotto speck e zucchine', 
4: 'Insalata di riso', 
5: 'Salmone con verdurine al forno', 
6: 'Minestra d\'avena', 
7: 'Pasta pesto, sugo, burro', 
8: 'Spätzli agli spinaci', 
9: 'Curry rosso al latte di cocco', 
10: 'Patate e fagiolini verdi al vapore', 
11: 'Minestra carote e patate e braciole', 
12: 'Pasta salmone e panna', 
13: 'Omelette con zucchine a cerchiolini', 
14: 'Fajitas alla carne o tofu', 
15: 'Pollo e patate al forno', 
16: 'Tortilla espanola', 
17: 'Risotto zafferano', 
18: 'Spätzli', 
19: 'Polenta', 
20: 'Pasta carbonara', 
21: 'Carne con insalata', 
22: 'Berner Rösti', 
23: 'Lasagne', 
24: 'Insalata di riso', 
25: 'Panizza', 
26: 'Focaccia di recco', 
27: 'Minestrina con pastina', 
28: 'Risotto speck e zucchine', 
29: 'Erdnusspoulet con riso ', 
30: 'Minestra carote e patate e braciole', 
31: 'Polpette al pomodoro con puree o polenta'
};
