var menus08 = {
1: 'Carne con insalata', 
2: 'Spätzli', 
3: 'Ossibuchi di vitello con puree', 
4: 'Insalata di riso', 
5: 'Flammkuchen', 
6: 'Pasta carbonara', 
7: 'Risotto zafferano', 
8: 'Curry rosso al latte di cocco', 
9: 'Polenta', 
10: 'Spätzli agli spinaci', 
11: 'Püree', 
12: 'Lasagne', 
13: 'Risotto salmone e verdurine', 
14: 'Hummus con patate o fajitas', 
15: 'Erdnusspoulet con riso ', 
16: 'Focaccia di recco', 
17: 'Pizza', 
18: 'Patate e fagiolini verdi al vapore', 
19: 'Crèpes ricotta e spinaci', 
20: 'Polpette al pomodoro con puree o polenta', 
21: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
22: 'Berner Rösti', 
23: 'Fajitas alla carne o tofu', 
24: 'Salmone con verdurine al forno', 
25: 'Spätzli', 
26: 'Lenticchie con sugo di pomodoro e verdurine', 
27: 'Insalata pomodoro mozzarella', 
28: 'Pasta carbonara', 
29: 'Spezzatino con puree o polenta', 
30: 'Chili con carne e riso', 
31: 'Minestra d\'avena'
};
