var menus09 = {
1: 'Pasta bolognese', 
2: 'Polenta', 
3: 'Omelette con zucchine a cerchiolini', 
4: 'Curry rosso al latte di cocco', 
5: 'Tortilla espanola', 
6: 'Focaccia di recco', 
7: 'Pollo e patate al forno', 
8: 'Hummus con patate o fajitas', 
9: 'Gratin di patate', 
10: 'Pasta salmone e panna', 
11: 'Salmone con verdurine al forno', 
12: 'Insalata pomodoro mozzarella', 
13: 'Pizza', 
14: 'Fajitas alla carne o tofu', 
15: 'Carne con insalata', 
16: 'Risotto speck e zucchine', 
17: 'Pasta carbonara', 
18: 'Polenta', 
19: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
20: 'Berner Rösti', 
21: 'Crèpes ricotta e spinaci', 
22: 'Focaccia di recco', 
23: 'Panizza', 
24: 'Insalatona à la jiji', 
25: 'Spezzatino con puree o polenta', 
26: 'Hummus con patate o fajitas', 
27: 'Curry rosso al latte di cocco', 
28: 'Tortilla espanola', 
29: 'Pasta salmone e panna', 
30: 'Patate e fagiolini verdi al vapore'
};
