var menus11 = {
1: 'Curry rosso al latte di cocco', 
2: 'Minestra d\'avena', 
3: 'Pasta bolognese', 
4: 'Fajitas alla carne o tofu', 
5: 'Risotto zafferano', 
6: 'Patate e fagiolini verdi al vapore', 
7: 'Tortilla espanola', 
8: 'Pollo e patate al forno', 
9: 'Insalata pomodoro mozzarella', 
10: 'Pizza', 
11: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
12: 'Polenta', 
13: 'Minestrina con pastina', 
14: 'Spätzli', 
15: 'Spätzli agli spinaci', 
16: 'Ossibuchi di vitello con puree', 
17: 'Polpette al pomodoro con puree o polenta', 
18: 'Gratin di patate', 
19: 'Pasta pesto, sugo, burro', 
20: 'Pasta bolognese', 
21: 'Hummus con patate o fajitas', 
22: 'Lenticchie con sugo di pomodoro e verdurine', 
23: 'Fajitas alla carne o tofu', 
24: 'Crèpes ricotta e spinaci', 
25: 'Berner Rösti', 
26: 'Focaccia di recco', 
27: 'Panizza', 
28: 'Insalata di riso', 
29: 'Püree', 
30: 'Spezzatino con puree o polenta', 
31: 'Spätzli'
};
