var menus07 = {
1: 'Polenta', 
2: 'Erdnusspoulet con riso ', 
3: 'Püree', 
4: 'Pasta pesto, sugo, burro', 
5: 'Carne con insalata', 
6: 'Flammkuchen', 
7: 'Salmone con verdurine al forno', 
8: 'Risotto zafferano', 
9: 'Panizza', 
10: 'Tortilla espanola', 
11: 'Fajitas alla carne o tofu', 
12: 'Risotto salmone e verdurine', 
13: 'Insalata di riso', 
14: 'Minestra carote e patate e braciole', 
15: 'Spezzatino con puree o polenta', 
16: 'Patate e fagiolini verdi al vapore', 
17: 'Minestra d\'avena', 
18: 'Patate a spicchi al forno', 
19: 'Erdnusspoulet con riso ', 
20: 'Crèpes ricotta e spinaci', 
21: 'Pollo e patate al forno', 
22: 'Minestrina con pastina', 
23: 'Focaccia di recco', 
24: 'Lasagne', 
25: 'Spätzli agli spinaci', 
26: 'Pasta pesto, sugo, burro', 
27: 'Lenticchie con sugo di pomodoro e verdurine', 
28: 'Flammkuchen', 
29: 'Berner Rösti', 
30: 'Spätzli', 
31: 'Chili con carne e riso'
};
