var menus02 = {
1: 'Hummus con patate o fajitas', 
2: 'Risotto salmone e verdurine', 
3: 'Salmone con verdurine al forno', 
4: 'Lenticchie con sugo di pomodoro e verdurine', 
5: 'Crèpes ricotta e spinaci', 
6: 'Polpette al pomodoro con puree o polenta', 
7: 'Pasta pesto, sugo, burro', 
8: 'Flammkuchen', 
9: 'Spätzli agli spinaci', 
10: 'Berner Rösti', 
11: 'Insalata di riso', 
12: 'Focaccia di recco', 
13: 'Pasta carbonara', 
14: 'Fajitas alla carne o tofu', 
15: 'Pasta salmone e panna', 
16: 'Omelette con zucchine a cerchiolini', 
17: 'Minestra d\'avena', 
18: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
19: 'Salmone con verdurine al forno', 
20: 'Patate a spicchi al forno', 
21: 'Gratin di patate', 
22: 'Chili con carne e riso', 
23: 'Tortilla espanola', 
24: 'Pizza', 
25: 'Insalatona à la jiji', 
26: 'Risotto salmone e verdurine', 
27: 'Insalata di riso', 
28: 'Curry rosso al latte di cocco'
};
