var menus06 = {
1: 'Pizza', 
2: 'Pasta salmone e panna', 
3: 'Insalatona à la jiji', 
4: 'Omelette con zucchine a cerchiolini', 
5: 'Risotto zafferano', 
6: 'Ossibuchi di vitello con puree', 
7: 'Tortilla espanola', 
8: 'Minestra d\'avena', 
9: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
10: 'Focaccia di recco', 
11: 'Fajitas alla carne o tofu', 
12: 'Insalata pomodoro mozzarella', 
13: 'Polpette al pomodoro con puree o polenta', 
14: 'Püree', 
15: 'Lasagne', 
16: 'Gratin di patate', 
17: 'Carne con insalata', 
18: 'Spätzli agli spinaci', 
19: 'Insalatona à la jiji', 
20: 'Salmone con verdurine al forno', 
21: 'Pasta carbonara', 
22: 'Flammkuchen', 
23: 'Berner Rösti', 
24: 'Erdnusspoulet con riso ', 
25: 'Minestra d\'avena', 
26: 'Risotto salmone e verdurine', 
27: 'Risotto zafferano', 
28: 'Curry rosso al latte di cocco', 
29: 'Risotto speck e zucchine', 
30: 'Crèpes ricotta e spinaci'
};
