var menus10 = {
1: 'Tortilla espanola', 
2: 'Minestrina con pastina', 
3: 'Patate a spicchi al forno', 
4: 'Minestra d\'avena', 
5: 'Spätzli', 
6: 'Carne con insalata', 
7: 'Lasagne', 
8: 'Ossibuchi di vitello con puree', 
9: 'Erdnusspoulet con riso ', 
10: 'Curry rosso al latte di cocco', 
11: 'Risotto salmone e verdurine', 
12: 'Polenta', 
13: 'Flammkuchen', 
14: 'Insalatona à la jiji', 
15: 'Chili con carne e riso', 
16: 'Hummus con patate o fajitas', 
17: 'Pasta salmone e panna', 
18: 'Pasta pesto, sugo, burro', 
19: 'Pollo e patate al forno', 
20: 'Minestra d\'avena', 
21: 'Crèpes ricotta e spinaci', 
22: 'Pizza', 
23: 'Insalata pomodoro mozzarella', 
24: 'Fajitas alla carne o tofu', 
25: 'Spätzli', 
26: 'Minestrina con pastina', 
27: 'Insalata di riso', 
28: 'Risotto salmone e verdurine', 
29: 'Curry rosso al latte di cocco', 
30: 'Minestra carote e patate e braciole', 
31: 'Carne con insalata'
};
