var menus03 = {
1: 'Tortilla espanola', 
2: 'Risotto salmone e verdurine', 
3: 'Pasta bolognese', 
4: 'Fajitas alla carne o tofu', 
5: 'Ossibuchi di vitello con puree', 
6: 'Omelette con zucchine a cerchiolini', 
7: 'Püree', 
8: 'Gratin di patate', 
9: 'Chili con carne e riso', 
10: 'Minestra d\'avena', 
11: 'Flammkuchen', 
12: 'Insalata di riso', 
13: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
14: 'Insalatona à la jiji', 
15: 'Spezzatino con puree o polenta', 
16: 'Polpette al pomodoro con puree o polenta', 
17: 'Insalata pomodoro mozzarella', 
18: 'Polenta', 
19: 'Pasta pesto, sugo, burro', 
20: 'Lasagne', 
21: 'Hummus con patate o fajitas', 
22: 'Panizza', 
23: 'Tortilla espanola', 
24: 'Curry rosso al latte di cocco', 
25: 'Spätzli agli spinaci', 
26: 'Risotto zafferano', 
27: 'Patate a spicchi al forno', 
28: 'Erdnusspoulet con riso ', 
29: 'Patate e fagiolini verdi al vapore', 
30: 'Risotto salmone e verdurine', 
31: 'Minestra d\'avena'
};
