var menus10 = {
1: 'Pollo e patate al forno', 
2: 'Flammkuchen', 
3: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
4: 'Püree', 
5: 'Risotto salmone e verdurine', 
6: 'Minestra carote e patate e braciole', 
7: 'Pasta bolognese', 
8: 'Risotto zafferano', 
9: 'Pizza', 
10: 'Berner Rösti', 
11: 'Chili con carne e riso', 
12: 'Crèpes ricotta e spinaci', 
13: 'Hummus con patate o fajitas', 
14: 'Fajitas alla carne o tofu', 
15: 'Curry rosso al latte di cocco', 
16: 'Lasagne', 
17: 'Pasta pesto, sugo, burro', 
18: 'Spätzli agli spinaci', 
19: 'Salmone con verdurine al forno', 
20: 'Flammkuchen', 
21: 'Minestrina con pastina', 
22: 'Ossibuchi di vitello con puree', 
23: 'Tortilla espanola', 
24: 'Focaccia di recco', 
25: 'Gratin di patate', 
26: 'Lenticchie con sugo di pomodoro e verdurine', 
27: 'Insalata pomodoro mozzarella', 
28: 'Risotto speck e zucchine', 
29: 'Insalatona à la jiji', 
30: 'Minestra d\'avena', 
31: 'Spätzli'
};
