var menus04 = {
1: 'Patate e fagiolini verdi al vapore', 
2: 'Flammkuchen', 
3: 'Ossibuchi di vitello con puree', 
4: 'Chili con carne e riso', 
5: 'Risotto zafferano', 
6: 'Crèpes ricotta e spinaci', 
7: 'Pasta carbonara', 
8: 'Focaccia di recco', 
9: 'Spätzli agli spinaci', 
10: 'Insalata pomodoro mozzarella', 
11: 'Risotto speck e zucchine', 
12: 'Minestrina con pastina', 
13: 'Polenta', 
14: 'Pasta bolognese', 
15: 'Püree', 
16: 'Risotto salmone e verdurine', 
17: 'Pizza', 
18: 'Lasagne', 
19: 'Pasta salmone e panna', 
20: 'Carne con insalata', 
21: 'Patate e fagiolini verdi al vapore', 
22: 'Insalatona à la jiji', 
23: 'Chili con carne e riso', 
24: 'Curry rosso al latte di cocco', 
25: 'Lenticchie con sugo di pomodoro e verdurine', 
26: 'Risotto zafferano', 
27: 'Insalata di riso', 
28: 'Minestra d\'avena', 
29: 'Ossibuchi di vitello con puree', 
30: 'Erdnusspoulet con riso '
};
