var menus03 = {
1: 'Tortilla espanola', 
2: 'Pasta pesto, sugo, burro', 
3: 'Lenticchie con sugo di pomodoro e verdurine', 
4: 'Pasta carbonara', 
5: 'Salmone con verdurine al forno', 
6: 'Curry rosso al latte di cocco', 
7: 'Gratin di patate', 
8: 'Polpette al pomodoro con puree o polenta', 
9: 'Patate a spicchi al forno', 
10: 'Insalata pomodoro mozzarella', 
11: 'Omelette con zucchine a cerchiolini', 
12: 'Focaccia di recco', 
13: 'Risotto zafferano', 
14: 'Risotto speck e zucchine', 
15: 'Insalata di riso', 
16: 'Carne con insalata', 
17: 'Minestra d\'avena', 
18: 'Panizza', 
19: 'Flammkuchen', 
20: 'Lenticchie con sugo di pomodoro e verdurine', 
21: 'Fajitas alla carne o tofu', 
22: 'Pasta bolognese', 
23: 'Risotto salmone e verdurine', 
24: 'Pollo e patate al forno', 
25: 'Minestrina con pastina', 
26: 'Gratin di patate', 
27: 'Insalata pomodoro mozzarella', 
28: 'Crèpes ricotta e spinaci', 
29: 'Patate a spicchi al forno', 
30: 'Ossibuchi di vitello con puree', 
31: 'Insalata di riso'
};
