var menus08 = {
1: 'Pasta salmone e panna', 
2: 'Risotto salmone e verdurine', 
3: 'Salmone con verdurine al forno', 
4: 'Panizza', 
5: 'Ossibuchi di vitello con puree', 
6: 'Hummus con patate o fajitas', 
7: 'Crèpes ricotta e spinaci', 
8: 'Insalata pomodoro mozzarella', 
9: 'Tortilla espanola', 
10: 'Insalata di riso', 
11: 'Erdnusspoulet con riso ', 
12: 'Fajitas alla carne o tofu', 
13: 'Pasta bolognese', 
14: 'Minestrina con pastina', 
15: 'Insalatona à la jiji', 
16: 'Pollo e patate al forno', 
17: 'Risotto zafferano', 
18: 'Minestra d\'avena', 
19: 'Curry rosso al latte di cocco', 
20: 'Pizza', 
21: 'Patate e fagiolini verdi al vapore', 
22: 'Spezzatino con puree o polenta', 
23: 'Minestra carote e patate e braciole', 
24: 'Gratin di patate', 
25: 'Spätzli', 
26: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
27: 'Erdnusspoulet con riso ', 
28: 'Lenticchie con sugo di pomodoro e verdurine', 
29: 'Patate a spicchi al forno', 
30: 'Salmone con verdurine al forno', 
31: 'Insalatona à la jiji'
};
