var menus04 = {
1: 'Chili con carne e riso', 
2: 'Omelette con zucchine a cerchiolini', 
3: 'Minestrina con pastina', 
4: 'Focaccia di recco', 
5: 'Curry rosso al latte di cocco', 
6: 'Polpette al pomodoro con puree o polenta', 
7: 'Pasta carbonara', 
8: 'Gratin di patate', 
9: 'Insalata di riso', 
10: 'Hummus con patate o fajitas', 
11: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
12: 'Flammkuchen', 
13: 'Fajitas alla carne o tofu', 
14: 'Minestra d\'avena', 
15: 'Pizza', 
16: 'Püree', 
17: 'Lasagne', 
18: 'Spätzli', 
19: 'Erdnusspoulet con riso ', 
20: 'Chili con carne e riso', 
21: 'Minestra carote e patate e braciole', 
22: 'Polpette al pomodoro con puree o polenta', 
23: 'Risotto speck e zucchine', 
24: 'Patate e fagiolini verdi al vapore', 
25: 'Insalata di riso', 
26: 'Spätzli agli spinaci', 
27: 'Pasta bolognese', 
28: 'Risotto salmone e verdurine', 
29: 'Risotto zafferano', 
30: 'Pollo e patate al forno'
};
