var menus09 = {
1: 'Pasta pesto, sugo, burro', 
2: 'Chili con carne e riso', 
3: 'Risotto zafferano', 
4: 'Flammkuchen', 
5: 'Minestra carote e patate e braciole', 
6: 'Püree', 
7: 'Panizza', 
8: 'Crèpes ricotta e spinaci', 
9: 'Patate e fagiolini verdi al vapore', 
10: 'Pollo e patate al forno', 
11: 'Fajitas alla carne o tofu', 
12: 'Minestra d\'avena', 
13: 'Erdnusspoulet con riso ', 
14: 'Insalatona à la jiji', 
15: 'Curry rosso al latte di cocco', 
16: 'Patate a spicchi al forno', 
17: 'Insalata pomodoro mozzarella', 
18: 'Spätzli agli spinaci', 
19: 'Risotto speck e zucchine', 
20: 'Lasagne', 
21: 'Carne con insalata', 
22: 'Pasta salmone e panna', 
23: 'Polenta', 
24: 'Spezzatino con puree o polenta', 
25: 'Tortilla espanola', 
26: 'Lenticchie con sugo di pomodoro e verdurine', 
27: 'Risotto zafferano', 
28: 'Pizza', 
29: 'Fajitas alla carne o tofu', 
30: 'Salmone con verdurine al forno'
};
