var menus08 = {
1: 'Berner Rösti', 
2: 'Chili con carne e riso', 
3: 'Fajitas alla carne o tofu', 
4: 'Crèpes ricotta e spinaci', 
5: 'Pasta bolognese', 
6: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
7: 'Carne con insalata', 
8: 'Insalata pomodoro mozzarella', 
9: 'Hummus con patate o fajitas', 
10: 'Lenticchie con sugo di pomodoro e verdurine', 
11: 'Spätzli agli spinaci', 
12: 'Püree', 
13: 'Minestra d\'avena', 
14: 'Risotto zafferano', 
15: 'Focaccia di recco', 
16: 'Pasta pesto, sugo, burro', 
17: 'Pizza', 
18: 'Patate e fagiolini verdi al vapore', 
19: 'Risotto speck e zucchine', 
20: 'Pasta salmone e panna', 
21: 'Insalata di riso', 
22: 'Polpette al pomodoro con puree o polenta', 
23: 'Spezzatino con puree o polenta', 
24: 'Polenta', 
25: 'Omelette con zucchine a cerchiolini', 
26: 'Crèpes ricotta e spinaci', 
27: 'Hummus con patate o fajitas', 
28: 'Insalatona à la jiji', 
29: 'Flammkuchen', 
30: 'Lenticchie con sugo di pomodoro e verdurine', 
31: 'Risotto salmone e verdurine'
};
