var menus12 = {
1: 'Pollo e patate al forno', 
2: 'Omelette con zucchine a cerchiolini', 
3: 'Püree', 
4: 'Insalata pomodoro mozzarella', 
5: 'Pasta bolognese', 
6: 'Fajitas alla carne o tofu', 
7: 'Spezzatino con puree o polenta', 
8: 'Pasta pesto, sugo, burro', 
9: 'Crèpes ricotta e spinaci', 
10: 'Pizza', 
11: 'Risotto salmone e verdurine', 
12: 'Insalata di riso', 
13: 'Berner Rösti', 
14: 'Erdnusspoulet con riso ', 
15: 'Pasta carbonara', 
16: 'Lenticchie con sugo di pomodoro e verdurine', 
17: 'Polpette al pomodoro con puree o polenta', 
18: 'Minestra d\'avena', 
19: 'Chili con carne e riso', 
20: 'Minestrina con pastina', 
21: 'Curry rosso al latte di cocco', 
22: 'Insalatona à la jiji', 
23: 'Püree', 
24: 'Fajitas alla carne o tofu', 
25: 'Pasta salmone e panna', 
26: 'Patate a spicchi al forno', 
27: 'Risotto zafferano', 
28: 'Flammkuchen', 
29: 'Spezzatino con puree o polenta', 
30: 'Pasta pesto, sugo, burro', 
31: 'Hummus con patate o fajitas'
};
