var menus = {
1: 'Crèpes ricotta e spinaci', 
2: 'Minestra d\'avena', 
3: 'Panizza', 
4: 'Polpette al pomodoro con puree o polenta', 
5: 'Omelette con zucchine a cerchiolini', 
6: 'Insalatona à la jiji', 
7: 'Pollo e patate al forno', 
8: 'Polenta', 
9: 'Pasta pesto, sugo, burro', 
10: 'Insalata di riso', 
11: 'Risotto zafferano', 
12: 'Pasta bolognese', 
13: 'Berner Rösti', 
14: 'Risotto speck e zucchine', 
15: 'Hummus con patate o fajitas', 
16: 'Flammkuchen', 
17: 'Gratin di patate', 
18: 'Spätzli agli spinaci', 
19: 'Pasta salmone e panna', 
20: 'Insalata pomodoro mozzarella', 
21: 'Minestrina con pastina', 
22: 'Chili con carne e riso', 
23: 'Minestra carote e patate e braciole', 
24: 'Lasagne', 
25: 'Spätzli', 
26: 'Fajitas alla carne o tofu', 
27: 'Salmone con verdurine al forno', 
28: 'Patate e fagiolini verdi al vapore', 
29: 'Pasta al currygiallo, latte di cocco e Chinakohl', 
30: 'Carne con insalata'
};